name: "build"
on:
#  push:
#    branches: [ $default-branch ]
#  pull_request:
#    branches: [ $default-branch ]
  workflow_call:

jobs:
  # build package
  build:
    name: Build Package
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      - uses: actions/checkout@v4
      - name: "Set up Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: "Install Package"
        run: npm ci
      - name: "run script"
        run: npm run build

