name: publish
on:
  release:
    types: [ created ]

jobs:
  build: # call main.yml
    uses: "em-d3v/em-pkg/.github/workflows/main.yml@main"
#    name: Build Package
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        node-version: [ 18.x, 20.x ]
#    steps:
#      - uses: actions/checkout@v4
#      - name: "Set up Node.js"
#        uses: actions/setup-node@v3
#        with:
#          node-version: ${{ matrix.node-version }}
#          cache: 'npm'
#
#      - name: "Install Package"
#        run: npm ci
#      - name: "Build"
#        run: npm run build
#      - run: npm test
  publish-npm:
    runs-on: ubuntu-latest
    name: publish to npm
    strategy:
      matrix:
        node-version: [ 20.3.1 ]
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: ${{ secrets.npm_registry }}
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
#    publish-gp:
#      name: publish - github packages
#      runs-on: ubuntu-latest
#      permissions:
#          contents: read
#          packages: write
#      steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-node@v3
#        with:
#          node-version: 16
#          registry-url: https://npm.pkg.github.com/
#      - run: npm ci
#      - run: npm publish
#        env:
#          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
